// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_progress
Rcpp::CharacterVector test_progress();
RcppExport SEXP progresstest_test_progress() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_progress());
    return __result;
END_RCPP
}
// test_units
Rcpp::CharacterVector test_units();
RcppExport SEXP progresstest_test_units() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_units());
    return __result;
END_RCPP
}
